apiVersion: v1
kind: ReplicationController
metadata:
  name: couchbase-master-controller
spec:
  replicas: 1
  selector:
    app: couchbase-master-pod
  template:
    metadata:
      labels:
        app: couchbase-master-pod
    spec:
      containers:
      - name: couchbase-master
        image: cosmic/couchbase
        imagePullPolicy: Never
        env:
          - name: TYPE
            value: "MASTER"
        ports:
          - name: cb-console-port
            containerPort: 8091
          - name: cb-query-port
            containerPort: 8093
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-webconsole-service
  labels:
    app: couchbase-master-service
spec:
  type: NodePort
  selector:
    app: couchbase-master-pod
  ports:
    - port: 8091
      targetPort: cb-console-port
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-query-service
  labels:
    app: couchbase-master-service
spec:
  type: NodePort
  selector:
    app: couchbase-master-pod
  ports:
    - port: 8093
      targetPort: cb-query-port
