apiVersion: v1
kind: ReplicationController
metadata:
  name: couchbase-master-controller
spec:
  replicas: 1
  selector:
    app: couchbase-master-pod
  template:
    metadata:
      labels:
        app: couchbase-master-pod
    spec:
      containers:
      - name: couchbase-master
        image: cosmic/couchbase
        imagePullPolicy: Never
        env:
          - name: TYPE
            value: "MASTER"
        ports:
        - name: couchbase-port
          containerPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-service
  labels:
    app: couchbase-master-service
spec:
  type: NodePort
  selector:
    app: couchbase-master-pod
  ports:
    - port: 8091
      targetPort: couchbase-port